when:
  event: [manual]

steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile
      platforms: linux/amd64
      repo: mrmn/pdfding
      registry: docker.io
      tags: latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: DOCKER_TOKEN
