version: '3'

services:
  pdfding:
    container_name: pdfding
    image: mrmn/pdfding:latest
    volumes:
      - media:/home/nonroot/pdfding/media
    environment:
      SECRET_KEY: some_secret
      HOST_NAME: 127.0.0.1
      CSRF_COOKIE_SECURE: FALSE
      SESSION_COOKIE_SECURE: FALSE
      DATABASE_TYPE: POSTGRES
      POSTGRES_PASSWORD: pdfding
#      # use this if you want to use OIDC
#      OIDC_CLIENT_ID: "pdfding"
#      OIDC_CLIENT_SECRET: "client_secret"
#      OIDC_AUTH_URL: "https://auth.pdfding.com/.well-known/openid-configuration"
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: pdfding
      POSTGRES_USER: pdfding
      POSTGRES_PASSWORD: pdfding
      POSTGRES_PORT: 5432

volumes:
  media:
  postgres_data: