when:
  - event: tag
  - event: manual
  - event: push
    path:
      include: [ '.woodpecker/e2e.Dockerfile', 'pyproject.toml', 'package.json' ]
  - event: pull_request
steps:
  publish_dry_run:
    when:
      - event: pull_request
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile
      platforms: linux/amd64
      dry_run: true
      repo: mrmn/pdfding
      tags: latest
  publish_tag:
    when:
      - event: tag
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile
      platforms: linux/amd64, linux/arm64/v8
      repo: mrmn/pdfding
      registry: docker.io
      tags: latest, ${CI_COMMIT_TAG}
      username: ${CI_REPO_OWNER}
      password:
        from_secret: DOCKER_TOKEN
  publish_manual:
    when:
      - event: manual
        evaluate: 'TAG != ""'
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile
      platforms: linux/amd64
      repo: mrmn/pdfding
      registry: docker.io
      tags: ${TAG}
      username: ${CI_REPO_OWNER}
      password:
        from_secret: DOCKER_TOKEN
  build-e2e-image:
    when:
      - event: manual
        evaluate: 'BUILD_E2E == "TRUE"'
      - event: push
        evaluate: 'CI_COMMIT_AUTHOR == CI_REPO_OWNER'
        path:
          include: [ '.woodpecker/e2e.Dockerfile', 'pyproject.toml', 'package.json' ]
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: .woodpecker/e2e.Dockerfile
      platforms: linux/amd64
      repo: mrmn/pdfding_e2e
      registry: docker.io
      tags: 2024.08.02
      username: ${CI_REPO_OWNER}
      password:
        from_secret: DOCKER_TOKEN
