when:
  - event: manual
    evaluate: 'TAG == ""'
  - event: pull_request
    branch: master
    evaluate: 'CI_COMMIT_AUTHOR == CI_REPO_OWNER'
    path:
      include: [ 'pdfding/**/*.py', 'pdfding/**/*.html' ]

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 1
      lfs: false

steps:
  code-quality:
    image: python:3.12.4-slim
    depends_on: []
    commands:
      - pip install poetry==1.8.3
      - poetry install --without e2e
      - poetry run flake8
      - poetry run black . --check
      - poetry run bandit -x "**/tests/*,**/e2e/*" -r .
  unit-tests:
    image: python:3.12.4-slim
    depends_on: []
    commands:
      - apt-get update && apt-get install --no-install-recommends -y libmagic1
      - pip install poetry==1.8.3
      - poetry install --without e2e
      - cd pdfding
      - poetry run pytest admin backup pdf users --cov=admin --cov=backup --cov=pdf --cov=users --cov-fail-under=100
  e2e-tests:
    image: mrmn/pdfding_e2e:2024.08.04
    depends_on: []
    environment:
      E2E_TESTS: E2E_TESTS
    commands:
      - cd /app
      - for i in admin core e2e pdf templates users; do cp -R $CI_WORKSPACE/pdfding/$i/ pdfding; done
      - cp $CI_WORKSPACE/pdfding/manage.py pdfding
      - npx --yes tailwindcss -i $CI_WORKSPACE/pdfding/static/css/input.css -o pdfding/static/css/tailwind.css -c $CI_WORKSPACE/tailwind.config.js --minify
      - poetry run python -m pytest pdfding/e2e
