when:
  - event: manual
    evaluate: 'TAG == ""'
  - event: pull_request
    branch: master
    evaluate: 'CI_COMMIT_AUTHOR == CI_REPO_OWNER'

steps:
  code-quality:
    image: python:3.12.4-slim
    commands:
      - apt-get update && apt-get install --no-install-recommends -y libmagic1
      - pip install poetry==1.8.3
      - poetry install
      - poetry run flake8
      - poetry run black . --check
      - cd pdfding
      - poetry run pytest --cov=pdf --cov=users --cov-fail-under=100
