name: PdfDing Release

on:
  release:
    types:
      - released

jobs:
  publish_release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mrmn
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            CI_COMMIT_TAG=${{ github.event.release.tag_name }}
          push: true
          tags: |
            mrmn/pdfding:${{ github.event.release.tag_name }}
            mrmn/pdfding:latest
          platforms: linux/amd64,linux/arm64
  update_helm_chart:
    name: Update helm chart
    runs-on: ubuntu-latest
    needs: publish_release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install -r .github/workflows/scripts/requirements.txt
      - run: python .github/workflows/scripts/update_chart_yaml_after_release.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
